### ISSUE TITLE
Auf iPad uns Safari macOS muss bei edit Tageler immer die Zeit mit angepasst werden

### ISSUE THREAD

**Issue by Androwski** [tageler/tageler-frontend#104]
Getestet by Coxi
Auf Windows 10 und Chrome kein Problem.

**Comment by peschmae** [comment]
Works in every proper browser...

Now let's look if there is a bugreport open in the libraries handling date/time

**Comment by peschmae** [comment]
Safari, doesn't properly handle the timezone attached, to the datetime.
When interpreting the date fetched from the json API, it adds the required difference to the users local time, but when saving, it doesn't handle it properly

**Comment by peschmae** [comment]
When testing it on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date Safari returns the wrong values for the second date... Yay...

**Comment by peschmae** [comment]
I've rewrote quite a bit of the date handling code in 79cda5c325966543e1f9ebe825eb4c11a53a2dbe
I wasn't able to reproduce the error afterwards, but I'm not entirely sure if it fixed all the issues we have

**Comment by peschmae** [comment]
This was deployed to production.

Still awaiting feedback if it's fixed
