### ISSUE TITLE
Delete/Update Methods don't work correct with new backend

### ISSUE THREAD

**Issue by doutzi** [tageler/tageler-frontend#13]
- [x] "delete" removes all tagelers instead of one

- [x] Update-Form does not work because of checkout / contact

**Comment by doutzi** [comment]
Problems:

- [ ] Delete Method does not work (deletes nothing)

- [ ] Start-/End-Time in database is +2h when create tageler

**Comment by lebalz** [comment]
Update works, not pushed yet; delete talks to backend correctly aswell
