### ISSUE TITLE
Darstellung Tageler (generell)

### ISSUE THREAD

**Issue by doutzi** [tageler/tageler-frontend#27]
Frage zur Darstellung der Tageler:
Bisher zeigen wir überall (Adminseite, Tageler-Übersicht etc.) nur Tageler an, die am aktuellen Datum oder später stattfinden. Sollen irgendwo (z.B. auf einer extra "Vergangene Tageler" Seite) die bereits vergangenen Tageler auch in einer Liste dargestellt werden, damit man die Möglichkeit hat, vergangene Events noch einmal anzuschauen?

**Comment by hairmare** [comment]
ping @Androwski

**Comment by kevin-meister** [comment]
Da hier gerade alle assigned sind:
Welche Felder sollen alle required (nötig zum Erstellen eines neuen Tagelers) sein?
Alle Felder: Name (=Titel)*, Text, Einheit*, Start (Datum), Ende (Datum), Mitbringen*, Kleidung*, _Absagen bis, Absagen bei, Telefon, Email, Text_ (zur Absage), Bild
Die Felder mit einem * sind die, welche momentan pflicht sind
Start und Enddatum würde wohl Sinn machen, Text wäre für den iCal Kalendereintrag nützlich.

**Comment by hairmare** [comment]
Ich versuch mal hier zu antworten...

@doutzi die alten Tageler sollten im admin Bereich sichtbar sein.

An der Front werden die alten Tageler nicht angezeigt. Dabei soll ein Tageler erst am Ende des Tages vom Enddatum versteckt werden. User sollen am Tag der Aktivität diese auch wenn sie schon vorbei ist noch anschauen können. So können sie nachschauen bis wann sie gedauert haben soll.

**Comment by hairmare** [comment]
@kevin-meister Bei einem Tageler sind die meisten Felder obligatorisch, das Bild ist uns z. Bsp auch wichtig. Eine Ausnahme sind die Absage Infos welche etwas komplexer sind:

* Absagen bis: obligatorisch, per default "am Mittwoch vor der Aktivität"
* Absagen bei: obligatorisch, per default im Prinzip die erfassende Person (TBD)
* Telefon, Email: mindestens eines davon muss ausgefüllt sein
* Text (zur Absage): optional, eventl. mit default

Mitbringen und Kleidung sind für den Moment optionale Felder.
