### ISSUE TITLE
Group-Page

### ISSUE THREAD

**Issue by lebalz** [tageler/tageler-frontend#5]
- [x] Filterfunction to show only Tagelers of given Group
- [x] Show Tagelers ordered by date:
- current, when Tageler started but not ended right now (Tageler.start < Date.timeNow && Tageler.end >Date.timeNow)
- next (Tageler.start>Date.timeNow)
- don't display finished Tagelers (Tageler.end < Date.timeNow)

**Comment by doutzi** [comment]
Easy version of order tageler by date works --> filter function in API:

- tageler.find({"date" : { $gte: new Date(startDate).toISOString() }}, function(err, result)....)

so finished Tagelers are not shown. "Nächster Tageler" displays only one tageler at the  moment, even if two have the same date. Todo:

- [ ] find solution if more than one tageler have the same date and display all
