### ISSUE TITLE
Todays tageler isn't displayed anymore at 11am if it is Übungsfrei

### ISSUE THREAD

**Issue by peschmae** [tageler/tageler-frontend#51]
Happens in Admin, as well as the normal panel.

I created the 'Herbstferien' Tageler for today, but at 11am it's already no longer displayed.

Additionally, when I edit the tageler, it shows the date as 13.10.2017 instead of 14.10.2017.

I see two issues that might behappening there.
1. Timestamp saved in wrong timezone (probably not UTC)
Fixing that might already resolve the issue, depending on how the check is done which Tagelers to display.
2. Übungsfrei is saved without Time / or Start & End-Time both set to 00:00, instead of using 00:00 for start, and 23:59 for the end

**Comment by Androwski** [comment]
Zeitzone generell fixen, wir sind nicht UTC

**Comment by peschmae** [comment]
We seem to have a start of a timezone implementation in https://github.com/hairmare/tageler-frontend/commit/36d07cc64666460c97ee14a874ff9a5a2c31fb9a

**Comment by hairmare** [comment]
IMO tz should be stored as UTC, displaying them in the local timezone should be done on the ui. Irregardless of what tz we are in always using UTC on the storage backend is a best practice nevertheless.

**Comment by peschmae** [comment]
I've switched up the pipe which determines the tagelers to display (and in which order), to make use of the end date of the tageler, and include the time not only the date.
This is commited in https://github.com/peschmae/tageler-frontend/commit/f9add08864f5dec99ad3bfe6d0c4996fcefd991a

But I still need to tackle how to display it in the frontend using the users local time.
