### ISSUE TITLE
Datumsanzeige/auswahl für FF

### ISSUE THREAD

**Issue by Androwski** [tageler/tageler-frontend#54]
Sollte aber in der nächsten FF Version nativ kommen.

**Comment by peschmae** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date it will be included in FireFox 57, due to be released 28.11.2017

As we are aiming for usage of the app starting december 2017, I won't invest time into this one.

**Comment by peschmae** [comment]
Firefox 57 is released
