### ISSUE TITLE
API Authentication einfügen (admin Teil)

### ISSUE THREAD

**Issue by Androwski** [tageler/tageler-frontend#58]

**Comment by peschmae** [comment]
@hairmare Any idea how we are going to implement this?

We already setup the basic auth for the admin part on the website itself, but for the API that needs to be done differently I think.

**Comment by peschmae** [comment]
https://docs.angularjs.org/api/ng/service/$http
`withCredentials`

Might be enough, but needs testing

**Comment by peschmae** [comment]
Application side fix was commited in #72 but the apache config is currently hacked by hand, instead of properly done in ansible

**Comment by peschmae** [comment]
fixed in ansible as well
